apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
  namespace: stoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
        - name: maildev
          image: maildev/maildev
          env:
            - name: MAILDEV_SMTP_PORT
              value: "25"
            - name: MAILDEV_WEB_PORT
              value: "8080"
            - name: MAILDEV_INCOMING_USER
              value: "smtp"
            - name: MAILDEV_INCOMING_PASS
              value: "smtp"
          ports:
            - containerPort: 25
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maildev
  namespace: stoat
spec:
  selector:
    app: maildev
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: web
      port: 8080
      targetPort: 8080
