blank_issues_enabled: false
contact_links:
  - name: Stoat Community README
    url: https://git.episkopos.community/episk-pos/stoat-community
    about: Read reporting guidelines before opening an issue.
